### ISSUE TITLE
Strange behavior of observer formulas.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#101]
First question - are all observers defined by formulas? This was my thought.

Now, the real problem:

1) Initialize the simulation "black american girl" from the  tests-folder without intializing any parameters.
```
simModelXML1 <- "./tests/models/black american girl.xml"
dci_info1 = initSimulation(simModelXML1, whichInitParam = "none");
```
2) Get the formula string of the parameter "black american girl|Organism|VenousBlood|Plasma|CYP3A4|OBSConcentration"
```
paramPath = "black american girl|Organism|VenousBlood|Plasma|CYP3A4|OBSConcentration";
getObserverFormula(path_id = paramPath, DCI_Info = dci_info1 )$Value

[1] ""
```

Obviously, the returned string is empty. In the XML,  the observed is defined by a formula:

    <Observer id="155" entityId="We7b8hOxCkWYMPTXynoxKQ" name="OBSConcentration" path="black american girl|Organism|VenousBlood|Plasma|CYP3A4" unit="µmol/l" persistable="1" formulaId="156" />

    <ExplicitFormula id="156">
      <Equation>M/V</Equation>
      <ParameterList>
        <P alias="V" id="128" />
      </ParameterList>
      <VariableList>
        <V alias="M" id="141" />
      </VariableList>
    </ExplicitFormula>

One could argue that the formula has been "optimized".  However, if the simulation is initialized with initilizing all parameters:

3) ` dci_info1 = initSimulation(simModelXML1, whichInitParam = "all");`

A formula for the observer is returned!

```
getObserverFormula(path_id = paramPath, DCI_Info = dci_info1 )$Value
[1] "M/V"
```

How and why? This is against the logic of "initializing  parameters destroys formula"! Please advise.

**Comment by Yuri05** [comment]
In a "standard" simulation enzyme amount is constant over time (no synthesis or degradation processes are defined). Compartment volume is constant as well.

Thus the concentration observer formula `M/V` will be replaced with a constant value (`M(0)/V(0)`).

If the `Volume `parameter is initialized (which is the case if ALL parameters are initialized) - it's considered as (potentially) non-constant, so the whole formula of a concentration observer is non-const too. Thus the formula is kept (strictly speaking it will be replaced with `M(0)/V` internally)

**Comment by Yuri05** [comment]
>This is against the logic of "initializing parameters destroys formula"! 

"initializing parameters destroys formula **_of the parameters_**"

**Comment by PavelBal** [comment]
OK, though not intuitive, it is logical. Thank you.
