### ISSUE TITLE
OSP-Suite 7.3.0 not compatible with R 3.5.1

### ISSUE THREAD

**Issue by CandideThunder** [Open-Systems-Pharmacology/R-Toolbox#106]
A fresh install of the R, OSP Suite and the R-toolbox revealed in-compatibilities for both the 32bit and 64bit R version.

32bit:
```
Loading required package: MoBiToolboxForR
Error: package or namespace load failed for ‘MoBiToolboxForR’:
 package ‘MoBiToolboxForR’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

```

64bit:
```
Loading required package: MoBiToolboxForR
Failed with error:  ‘package ‘MoBiToolboxForR’ is not installed for 'arch = x64'’

```

**Comment by msevestre** [comment]
We will drop support for 32bit version in the upcoming release. The new version will be compatible with the latest R.
If you like to leave on the bleeding edge, you can use it already

**Comment by msevestre** [comment]
Download is here
https://ci.appveyor.com/project/open-systems-pharmacology-ci/r-toolbox/branch/develop/artifacts

**Comment by CandideThunder** [comment]
Bleeding edge is my castle and my home.

It worked fine on a small test project. Cool.
