### ISSUE TITLE
Feature request: getRHS()

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#107]
During workshops, attendees often ask where they can find the differential equations of the model.

While there is no such option im PK-Sim or MoBi, we could implement a toolbox-function that will return the right hand side of a provided species.

The output could be:
-RHS as a string,
-List of used parameters/species.

**Comment by Yuri05** [comment]
Isn't Matlab ODE export sufficient? It's not intended for being read by humans and thus the ODE representation is not very user friendly. But the complete RHS of a species is visible.

**Comment by StephanSchaller** [comment]
> Isn't Matlab ODE export sufficient?

Yes, I believe it is. But maybe we need a different kind of export format, now, and use a different kind of naming (Indexing species and parameters is rather hard to understand)?

**Comment by PavelBal** [comment]
>Isn't Matlab ODE export sufficient?

I believe it is not, because

>It's not intended for being read by humans and thus the ODE representation is not very user friendly.

;)

Now I actually see that this could be a very usefull feature to check which processes are applied to a certain species in a container.

**Comment by Yuri05** [comment]
>Now I actually see that this could be a very usefull feature to check which processes are applied to a certain species in a container.

In this case **_MoBi_** would be the right place to show this info, **_not the (R-)toolbox_**.
Because on the toolbox level all information about processes etc. is not available anymore.

However on the toolbox level we could get representation like this:
```
dX(1)/dt = R1+R2+...

X(1): VenousBlood/Plasma/Midazolam

R1: Q*C
Q: Bone/Blood flow Rate
C: Bone/Plasma/Midazolam/Concentration

R2: Q*C
Q: Brain/Blood flow Rate
C: Brain/Plasma/Midazolam/Concentration

...
```
The user must than track partial RHS (_R1, R2, ... in the example above_) back to the model processes manually

**Comment by StephanSchaller** [comment]
> However on the toolbox level we could get representation like this

Yes, I think this is a good way of presenting the info, as you would still want the references for the different variables shown.
And I think it would be harder (or not possible even) in MoBi as a merged "referenced Objects List" for a combined RHS (if we just add up i.e. combine formulas) could have duplicates of aliases.

**Comment by PavelBal** [comment]
>However on the toolbox level we could get representation like this:

Yes, this would be a good option.
