### ISSUE TITLE
xml encoding is ASCII?

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/R-Toolbox#109]
In case anyone ever tries editing the xml via R using the "XML" package, just note, when using `saveXML()` you need to set `encoding = "ASCII"` for initSimulation to be able to read the XML again.

We sure our xmls are UTF-8 encoded?

**Comment by msevestre** [comment]
What's the first line in your xml file? It should specify the encoding. Is maybe the save method from r removing it?

Load the file and save it right away and compare the files with a diff tool. Any difference?

**Comment by StephanSchaller** [comment]
>  What's the first line in your xml file? It should specify the encoding.

Yeah, I know, this line reads utf-8. R is indeed removing this line. Nevertheless, when I choose utf-8 when saving as xml again from R. I can't load the xml. If I choose ASCII, I can. 

However, the new xml is missing this first line <?xml…..>
 Probably an issue of the XML package and it is screwing up some (special) characters when choosing utf-8. Will try the compare.

**Comment by StephanSchaller** [comment]
Aaaaw , whatever...now the files match so it seems it was the guy behind the screen beeing the problem ;-)
