### ISSUE TITLE
It seems that the download path for R 3.5.1 windows has changed?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/R-Toolbox#113]
thus resulting in the build failing. This needs to be updated

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/develop/appveyor.yml#L24

**Comment by msevestre** [comment]
As long as this is not updated, the build will fail

**Comment by Yuri05** [comment]
It's https://cran.r-project.org/bin/windows/base/old/3.5.1/R-3.5.1-win.exe for 3.5.1 and
https://cran.r-project.org/bin/windows/base/old/3.5.2/R-3.5.2-win.exe for 3.5.2
(3.5.2 is also available under https://cran.r-project.org/bin/windows/base/R-3.5.2-win.exe ; if we take address with **_old_**, future buils will not fail)

@PavelBal Should we take 3.5.1 or upgrade to 3.5.2?

**Comment by PavelBal** [comment]
We can upgrade to 3.5.2, I don't see any problem with that.
