### ISSUE TITLE
model import

### ISSUE THREAD

**Issue by RKasp** [Open-Systems-Pharmacology/R-Toolbox#118]
Hello R-users,
Probably easy question, not sure it the right forum here: I need a bit guidance with regard to importing model.xml files.
I generated a simple model xml file in MoBi, e.g. from the warfarin template and import it in similar fashion as described during a workshop. I receive the following error message, even when trying the other options as described in the toolbox help section. However the workshop practice file worked
Thank you for your input how to solve this.
Best regards,
Rudiger

```
library(MoBiToolboxForResqLABS)
 library(parallel)
 simFolder ="C:/Users/rudigerk/Desktop/library/PBPK/pksim.QSP/R_PKSim_test/"
 modelName = "Warfarin_M";
modelPath = paste0(simFolder, modelName, ".xml");
myDCI = initSimulation(modelPath, whichInitParam = "all")

Error in initSimulation(modelPath, whichInitParam = "all") : 
  Validate of XML file "" failed:
At element: 
Error code: -1072898028
Url: 
Source Text: 
At line: 0
At line Pos: 0
Reason: Element '{http://www.systems-biology.com}TableFormulaWithXArgument' is unexpected according to content model of parent element '{http://www.systems-biology.com}FormulaList'.
Expecting: {http://www.systems-biology.com}Formula.
```

or also used:

```
initSimulation(XML = "C:/Users/rudigerk/Desktop/library/PBPK/pksim.QSP/R_PKSim_test/Warfarin_M.xml", ParamList = numeric(0), whichInitParam = "all", further_options = "", Version = "6_0", SimulationNumber = 1)
```

**Comment by msevestre** [comment]
@RKasp Sorry for the late reply. 

It seems that you are using another version from the R toolbox `MoBiToolboxForResqLABS` so I am not sure what has changed there and how it differs from the one distributed with the suite

From the look of it, it feels that you are using an outdated version of the schema that is used to validate the model structure

The version released with the suite contains TableFormulaWithXArgument
https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel.Schema/blob/master/OSPSuite.SimModel.xsd#L134

However this was added about 11 months ago. If you are for some reason referencing an older version of the schema, then this would explain WHY newer model cannot be loaded

@RKasp 
The file is called OSPSuite.SimModel.xsd. Can you check where you have this file on your system (and especially is the one used by R an older one?)

@PavelBal 
Do you know a way to see which Schema/SimModel version is loaded?

**Comment by PavelBal** [comment]
Dear Rudiger,

the current official version of the R-Toolbox already incorporates most of the bugfixes that were introduced in the esqLABS-adjusted version used in the workshop. I would suggest installing the official version (default location "C:\Program Files\Open Systems Pharmacology\MoBi Toolbox for R 7.4\MoBiToolboxForR_7.4.0.zip" ). You then have to adjust the first line of your code to

`library(MoBiToolboxForR)`

If this does not solve your issue, we will have to troubleshoot further.

**Comment by RKasp** [comment]
perfect, thank you, it works!
