### ISSUE TITLE
Run Toolbox on Linux

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/R-Toolbox#119]
To pick up the thread on [Linux](https://github.com/Open-Systems-Pharmacology/Forum/issues/197) (can't reopen myself):

Not to actually have the tools run on Linux, but have the Libraries (and Toolboxes) built for Linux so runs in Matlab/R can be run on Linux (-Clusters).

**Comment by msevestre** [comment]
Moved this issue to the R Toolbox has technical considerations do not need to pollute the forum

I would love to NOT use DCI and DCIR anymore and rely directly on a R => C++ integration. This would certainly allow for a nicer API too
