### ISSUE TITLE
PKSimCreateIndividual: reading endothelial calculation method from XML

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#121]
Two issues.

First - retrieving endothelial surface caluclation method from a provided initialized simulation does not work because of https://github.com/Open-Systems-Pharmacology/R-Toolbox/issues/76

Second - Formula strings are hard-coded, bad solution!

**Comment by Yuri05** [comment]
>First - retrieving endothelial surface caluclation method from a provided initialized simulation does not work because of #76

Why?

>Second - Formula strings are hard-coded, bad solution!

Suggestions? Calculation methods are not stored in XML and can be obtained only indirectly (e.g. via checking the formulas)

**Comment by PavelBal** [comment]
> Why?

This is how it is implemented in Matlab:

```
path_id='*|Neighborhoods|*_pls_*_int|Surface area (plasma/interstitial)';
    if existsParameter(path_id,simulationIndex,'parametertype','readOnly');
        tmp=getParameter(path_id,1,'Property','Formula','parametertype','readOnly');
        switch tmp{1}
            case 'k * f_vas_org * V_org'
                endothelialSurfaceAreaCalculationMethod='SurfaceAreaPlsInt_VAR1';
            case 'k * Q_org ^ beta'
                endothelialSurfaceAreaCalculationMethod='SurfaceAreaPlsInt_VAR3';
            otherwise
                endothelialSurfaceAreaCalculationMethod='SurfaceAreaPlsInt_VAR1';
        end
    else
```

For whatever reason, those parameters are treated as non-formula in R (see #76), so no comparison of fomrula string in the simulation with the pre-defined values are possible.

> Suggestions? Calculation methods are not stored in XML and can be obtained only indirectly (e.g. via checking the formulas)

No suggestions so far, just don't like the current solution. If you ever change the formula in the model (and be it just removing a space), the comparison will not work. A workaround could be to retrieve the reference strings from PK-Sim (they must be stored somewhere as constants?)?

**Comment by msevestre** [comment]
WOW. That code is...just wow

Why is it done like that and what does it do exactly? Is the goal to find out what methods were used?Is it for reporting purpose? 

I think we should export the used CM as a node in the SimModel.xml or as a separate file.

**Comment by PavelBal** [comment]
>Why is it done like that and what does it do exactly? Is the goal to find out what methods were used?Is it for reporting purpose?

Creating individual parameter sets from MatLab (and now R). I don't known which parameter would depend on the calculation method, and if this is necessary at all. Perhaps @Yuri05 can comment on this?
