### ISSUE TITLE
Integration of .Net-Bridge

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#123]
As R does not provide native methods to load .NET libraries, we must use external packages to implement creating individuals functionality. One solution would be to use the [.Net-Bridge](https://github.com/tr8dr/.Net-Bridge/tree/master) package.

How should the integradtion be implemented (I have no experience with that)? Should the MoBi-Toolbox be dependent on rDotNet and install the latter automatically from CRAN, or should we include rDotNet as source in our own?

**Comment by Yuri05** [comment]
@PavelBal Is .Net-Bridge an extension of [rDotNet](https://cran.r-project.org/web/packages/rDotNet/index.html )? Or how are they related to each other?

**Comment by PavelBal** [comment]
rDotNet is an R-Package that uses .Net-Bridge. In theory, installation of the rDotNet package should be sufficient. In practice, I had checkout the R-source code and make some adjustements so it would run under 64-bit..
