### ISSUE TITLE
Feature - getPathToPKSimInstallDir()

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#124]
Generate the path to PK-Sim installation directory to access the *.dll located within.

Currently, a hard-coded path will be used.

**Comment by Yuri05** [comment]
s. Matlab-implementation: https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox-Core/blob/b0f349751f671bf1c6b5a67ecd28337882a91851/code/auxiliaries/getPathToPKSimInstallDir.m#L15

**Comment by PavelBal** [comment]
This has been solved.
