### ISSUE TITLE
PKSimCreateIndividual: use distribution

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#125]
Implement creating individuals with parameter "useDistribution == TRUE".

**Comment by msevestre** [comment]
What does that mean?

**Comment by PavelBal** [comment]
Memo for myself to add the functionality of setting parameter useDistrubution to TRUE, as done in Matlab (I don't really know so far what it does).

**Comment by msevestre** [comment]
👍  ok thanks man
