### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by aelmokadem** [Open-Systems-Pharmacology/R-Toolbox#19]
Hi,
I have installed the MoBi R toolbox and it successfully unpacked but when I try to load the library, I get this error:

Error: package ‘MoBiToolboxForR’ is not installed for 'arch = x64'

**Comment by msevestre** [comment]
@Yuri05 are we supporting x64 architecture there?

**Comment by PavelBal** [comment]
No, you have to use the 32-bit version of R.

**Comment by aelmokadem** [comment]
Thanks Michael and Pavel.

**Comment by msevestre** [comment]
@Yuri05 should not we add something in the R readme? Or is it there already?

**Comment by PavelBal** [comment]
Or at least in OSPS-documentation. btw, the download-link to R-toolbox in the documentation leads to old systems-biology.com site.

**Comment by Yuri05** [comment]
Added 32bit note to R and Matlab-Toolbox-Readmes (was already in the system requirements in the Suite-Readme)
