### ISSUE TITLE
Missing 'OSPSuite.SimModel.xsd' in 7.2.0

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/R-Toolbox#26]
Not sure why, but the required file 'OSPSuite.SimModel.xsd' is missing in the /libs directory.

**Comment by msevestre** [comment]
@yuri05 this has been tested by someone or not?

**Comment by Yuri05** [comment]
Sure and `OSPSuite.SimModel.xsd` is included.

@StephanSchaller Which R package did you install? Which R version are you using? The R Toolbox is currently only available for the 32bit R (versions 3.3 or later).

In any case, you can copy the missing file from PK-Sim or MoBi installation folder into the libs-folder

**Comment by StephanSchaller** [comment]
@Yuri05. I installed OSP 7.2.0, with it Comes the RToolbox 7.2.0. and there in the /libs directory, the file is MISSING (It is also missing in the separate MoBiToolboxForR 7.2.0 package downloaded from Github).
I dowloaded the MoBiToolboxForR 7.1.0 separately and copied the file. 
That works ...
