### ISSUE TITLE
Round brackets () in path names should be escaped authomatically

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#27]
Path names which contain brackets, e.g., "Param (a)", must be specified as "Param \\(a\\)" by the user. This is inconvenient, and should be performed in the background.

Suggestion is to add

```
searchValue <- gsub('(', '\\(', searchValue, fixed = TRUE)
searchValue <- gsub(')', '\\)', searchValue, fixed = TRUE)

```
after this line

https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/e7d9bb1a5df01f8dcae845b83540d6bce616119b/src/code/findTableIndex.R#L39

**Comment by Yuri05** [comment]
@PavelBal Feel free to make a contribution via Pull Request :-)

**Comment by PavelBal** [comment]
Will gladly do :)

**Comment by msevestre** [comment]
@PavelBal +1

**Comment by CandideThunder** [comment]
Hi @PavelBal,
if you fix this, please consider: 1) It will break old code that was doing the escaping itself. Hence it may be better to create a new function. 
2) Internally, it uses RE, hence there are more characters with a special meaning that needs escaping, e.g. the '.', []{}

I tend to use a helper function to clean the path before putting it into the search:

```
cleanPathFun = function(searchValue) {
  # r toolbox uses regexp to find path, but not all special characters are correctly escaped
  # TODO file bug report and or submit patch
  searchValue <- gsub("(", "\\(", searchValue, 
                      fixed = TRUE)
  searchValue <- gsub(")", "\\)", searchValue, 
                      fixed = TRUE)
  searchValue <- gsub("[", "\\[", searchValue,
                      fixed = TRUE)
  searchValue <- gsub("]", "\\]", searchValue,
                      fixed = TRUE)
  
  return (searchValue)
}

```

**Comment by PavelBal** [comment]
@CandideThunder I see your point. Question is, now much of old code that will be broken is out there? I do no think that creating a new function that will work correctly instead of an existing function which is supposed to work correctly is a good idea, as it will just bring more confusion ("which function should I use?").

I would prefer to "fix" the existing function (i.e., do the escaping automatically) and add a warning message, if a parameter with the given path cannot be found and the given path contains the manual escaping, that the escaping is done automatically. This way, the errors (or the obsolete workarounds) in the existing code can be found quickly. The warning message could be removed in future releases to keep the code clean.

How do other see this? What should we agree on?

**Comment by msevestre** [comment]
@PavelBal I like your proposal. This is clearly a bug in the current code base and the only way forward is to correct the bug and ensure that clear warnings are shown when something is suddenly not working as you suggested

**Comment by CandideThunder** [comment]
Hi @PavelBal, you asked how much of the old code out there will break -- I think it will be *all* the old code out there, because this bug has been around ever and many queries do need the escaping. 
Despite of that, I agree that fixing this now should be the preferred way forward as the method is currently not behaving as the documentation says.

**Comment by msevestre** [comment]
@PavelBal This is also fixed with #34 correct?

**Comment by PavelBal** [comment]
Yepp.

**Comment by msevestre** [comment]
See #34 for fix as well

@PavelBal In your commit message, if you add the following "Fixes #xxx " then the link between issues will be done automatically

'Fixes' is important as it will also close the issue automatically
