### ISSUE TITLE
setSimulationTime should simply foward time points to SimModel instead of creating intervals

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/R-Toolbox#33]
see discussion here
https://github.com/Open-Systems-Pharmacology/R-Toolbox/issues/10

and code [here](https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/develop/src/code/setSimulationTime.R)

In my eyes, the current implementation is overly complicated. The method `setSimulationTime` should simply forward the given time points array "AS IS" to `SimModel` as discrete time values array are supported. 

The caller of the method would be responsible to define the interval as needed and the R code would do nothing more than forward the array by setting the expected properties into DCI_info

I do not see the need of supporting interval in R. The definition of a sequence is trivial in R via the `seq` method `e.g. seq(0,12,2)`

@Yuri05 @StephanSchaller @PavelBal 
Thoughts ?

**Comment by PavelBal** [comment]
Looking at the code, I understand that DCI_info takes the start and the end times, and the number of points, as input for the simulation time and pattern definition. Could you @msevestre show me an example where/how a descrete time values array is used?

And are distributions other than "Equidistant" supported and if yes, what could be the use of them?

**Comment by msevestre** [comment]
@PavelBal This would need to be changed in DCI_info interface probably
SimModel knows about those singular time points. We are using it when running a ParameterIdentification for example

OSPSuite.Core is using it [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/f75c2b2f6a639a8a8f27e4937358ad7819e87ba0/src/OSPSuite.Core/Domain/OutputSchema.cs#L25) or [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/f75c2b2f6a639a8a8f27e4937358ad7819e87ba0/src/OSPSuite.Core/Serialization/SimModel/DTO/OutputSchemaExport.cs#L12)

So while the interface might not be open, this is internally clearly supported.

>And are distributions other than "Equidistant" supported and if yes, what could be the use of them?

Not sure if anything else is supported but we wanted to ensure that this was possible to extend for future use. you could imagine that you want points between Start and End time with lots of point at the beginning and not so much at the end or the opposite. In MoBi, there is even an issue for that [here](https://github.com/Open-Systems-Pharmacology/MoBi/issues/222)

**Comment by PavelBal** [comment]
OK, in that case your proposed solution is definitely the clearest and the best. Then there would be no need in "non-equidistant" intervals, or multiple intervals with different resolutions.

A drawback of this approach is higher memory consumption - `seq(0, (60*24*365*10), 1)`  (now do not ask me why someone would like to simulate ten years and plot each single minute!) is definitely much larger then `"min = 0, max = (60*24*365*10), distance = 1)"`, but the drawback will probably remain of theoretical nature unless we want to run thousands of simulation in parallel or go to mobile platforms :D

**Comment by msevestre** [comment]
@PavelBal lol yeah. If someone wants to run something like that, the number of time points will not be the only problem :)

**Comment by PavelBal** [comment]
Not sure I can do much about it without knowing exactly how calls from R are forwarder to SimModelComp, i.e., having access to DCI and/or DCIR. Please correct me if I am wrong.

**Comment by msevestre** [comment]
@PavelBal As far as I know, all the magic is happening in SimModelComp. So what would need to be done in theory is extend SimModelComp to provide an entry point with the expected value

I think this is done by adding a port in the SimModelComp [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/master/src/OSPSuite.SimModelComp/OSPSuite_SimModelComp.xml#L44)

Here is also the code for [UpdateOutputTimeSchema](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/e13770dcf9f8878435183b74248e15851d1262d9/src/OSPSuite.SimModelComp/src/SimModelComp.cpp#L671) and [FillOutputSchemaInputTable](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/e13770dcf9f8878435183b74248e15851d1262d9/src/OSPSuite.SimModelComp/src/SimModelComp.cpp#L696). I am not sure exactly why there are two methods. One update the table from SimModel and the other one update SimModel from the table. Easiest way would be to create a new Table to handle discret points. Or we update the existing table. 

@Yuri05 Any suggestions?
