### ISSUE TITLE
New function request: getSolverWarnings()

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/R-Toolbox#36]
... as we already have for the Matlab Toolbox

**Comment by PavelBal** [comment]
Please assing to me.

**Comment by PavelBal** [comment]
@Yuri05 @StephanSchaller  Do you have an example of code that would produce such warnings? Matlab would be OK. I cannot test if I do not know how to produce warnings ;)

**Comment by Yuri05** [comment]
Set `MxStep `to a very low value (e.g. `<10`) and you will get warnings with virtually every simulation
(also set `StopOnWarnings = false`)

**Comment by PavelBal** [comment]
Thanks, works!

> (also set StopOnWarnings = false)

Just to be sure - in this case (MxStep = 9), the simulation always stops with an error, despite setting StopOnWarnings = false. Should it **not** stop? How does it behave in Matlab? If it should proceed without interrupting, then we just found another bug...

**Comment by PavelBal** [comment]
@StephanSchaller 
Can you please close? The function was implemented with https://github.com/Open-Systems-Pharmacology/R-Toolbox/pull/85

**Comment by StephanSchaller** [comment]
Thanks for the notice
