### ISSUE TITLE
new function request: compareSimulations()

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/R-Toolbox#37]
... as we already have for the Matlab Toolbox

**Comment by PavelBal** [comment]
Please define what exactly it should do (also a question for Matlab Toolbox maintainers, to keep the functionality consistent).

**Comment by StephanSchaller** [comment]
@KatrinCoboeken , @Yuri05 , do you have specifications for the Matlab Toolbox function we can build on?

**Comment by PavelBal** [comment]
Please assing to me.

**Comment by PavelBal** [comment]
compareSimulations() will take two initialized DCI_Info-objects and compare them. This is different to Matlab implementation, where comparison is done for two simulations stored as XML.

Comparing two DCI_Info makes more sense to me.

**Comment by KatrinCoboeken** [comment]
Yes I think that makes sense in R.
In Matlab the DCI_Info Objects are hidden, so it was done by initializing xmls, and then using the Objetcs.
