### ISSUE TITLE
Create x64 bit package of the R-Toolbox

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/R-Toolbox#40]
We have started the move to 64 bit, at least for the very core components. SimModel is now available in 64 bit and the next step would be to start moving the toolboxes to see if any issues arise

**Comment by msevestre** [comment]
@PavelBal @Stephanschaller
We are going to experimentally create a 64bit package of the R toolbox. This can be released even if the OSPSuite  is not 64bit compatible.

Do you know if there are any structural differences in the way a package should be created for 64bit?
Especially we copy all libs to a i386 folder at the moment for 32bit. Is it the same for 64? 

Any pointer would be appreciated

**Comment by PavelBal** [comment]
Unfortunately - no idea.

**Comment by msevestre** [comment]
Are there any 64bit packages out there using a similar c++ dependencies that we could look at?

**Comment by StephanSchaller** [comment]
[This](http://www.stats.ox.ac.uk/~ripley/Win64/W64porting.html) is what I found when browsing through the topic myself.
I think they also cover this topic.

**Comment by StephanSchaller** [comment]
@msevestre did that link provide any help?

**Comment by msevestre** [comment]
Haven't checked in details. I did a quick search for the folder i386 and it was not mentioned in the article.  My guess is that this article is for another use case but won't know for sure until I start working on it

**Comment by msevestre** [comment]
to be honest, my first try will be to copy the lib into an `x64` folder instead of `i386` folder and see if this is enough. That link you provided is about compiling components for x64 but we don't do that. 
@Yuri05 Could you compile a 64bit version of DCIR?

**Comment by msevestre** [comment]
What's the version of R that we should support here?

Latest R is 3.5.1
Latest R tool is 3.5

Are we happy with that?

**Comment by PavelBal** [comment]
Yes.

**Comment by msevestre** [comment]
@PavelBal @StephanSchaller 
I have a first version of the x64 bit package
https://ci.appveyor.com/api/buildjobs/s8lxrx2m9gqfvexa/artifacts/MoBiToolboxForR_7.4.0.zip

Could you try it and let me know if that works at all?

This requires version 3.5 of R

**Comment by msevestre** [comment]
When that works, we can merge #96

**Comment by PavelBal** [comment]
Great! Will run the unit tests tomorrow.

**Comment by msevestre** [comment]
I have no idea if I am doing anything wrong (and I probably am) but I am getting the following error when executing a simple code
`Error: object of type 'closure' is not subsettable`

This is the code 👍 
```
require(MoBiToolboxForR)
simModelXML <- "C:/projects/R-Toolbox/tests/models/Rabbit Caffein.xml"
standard_dci_info <- initSimulation(XML=simModelXML, whichInitParam="none")
inistandard_dci_info <- processSimulation(DCI_Info = standard_dci_info)
res = getSimulationResult(DCI_Info=standard_dci_info, path_id = "*Rabbit Caffein|Organism|VenousBlood|Plasma|Caffeine*")
getPKParameterForConcentration(res[,1], res[,2])
```

It throws already at `standard_dci_info <- initSimulation(XML=simModelXML, whichInitParam="none")`

It seems that the package is created properly. But well the code may not be compatible with R 3.5 anymore...

I loaded the package using the Install package method from R Studio. Packaged was installed successfully

**Comment by StephanSchaller** [comment]
I'll let Pavel handle this ;-)

**Comment by msevestre** [comment]
@PavelBal 
Let's try this guy instead
https://ci.appveyor.com/api/buildjobs/sfjeeclh6r82fgqk/artifacts/MoBiToolboxForR_7.4.0.zip

**Comment by PavelBal** [comment]
@msevestre MobiSettings searches in the "i386"-folder instead of "x64" for the library:

https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/9e54257b7cea079b20051bd621fd9b8abcee67e1/src/code/MobiSettings.R#L6

Must be changed to "x64".

**Comment by msevestre** [comment]
nice find.
Can you check my changes here 
https://github.com/Open-Systems-Pharmacology/R-Toolbox/pull/96/commits/42c36a9d9d751c4aea15b6fa6f47c1023cbf73ef

here the new package for you to try :)
https://ci.appveyor.com/api/buildjobs/dqrycglxe9mbw18h/artifacts/MoBiToolboxForR_7.4.0.zip

**Comment by msevestre** [comment]
PS: How can I install an old package and use a new one? Simply install it again?

**Comment by PavelBal** [comment]
> Can you check my changes here

Looks good.

> here the new package for you to try :)

It works! Unit test results are identical to those of 7.3.

> PS: How can I install an old package and use a new one? Simply install it again?

Not sure what you mean... The last installed version is always used.

**Comment by msevestre** [comment]
Sorry I mean uninstall and old package. 
I was wondering if it was as easy as install.package again. 
It is more or less (I had to close R Studio for changes to take effect)

**Comment by msevestre** [comment]
Did you get a chance to run the unit tests with the x64 version?
Cheers

**Comment by PavelBal** [comment]
> Did you get a chance to run the unit tests with the x64 version?

Yes:
>It works! Unit test results are identical to those of 7.3.

**Comment by msevestre** [comment]
Awesome. 

What's the procedure to run the unit tests?

**Comment by PavelBal** [comment]
> What's the procedure to run the unit tests?

Run the https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/develop/tests/DoRUnitTesting.R
Either "source" it - in this case you have to manually change the path to the toolbox:
https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/bd1ed46a5fbe6e4b0d0efa328a735c59d07dd2da/tests/DoRUnitTesting.R#L13

Or run it from consle like this:

```
cd /D c:\Program Files\R\R-3.5.0\bin\i386\
RScript "PathToYourLocalRepository\R-Toolbox\tests\DoRUnitTesting.R" "PathToYourLocalRepository/R-Toolbox/"
set VAR=%errorlevel%
ECHO %VAR%
pause
```

The script generates a "Protocol.html" in the "tests"-subfolder.

**Comment by msevestre** [comment]
cool thanks

**Comment by msevestre** [comment]
@PavelBal I just ran the tests and I had  a few that actually did not run. Is it what you have as well? 

```

Executing test function test.CheckParameterInSimulationNoneVariables  ... Timing stopped at: 0.71 0.02 0.72
Error in getTableParameter(path_id = path_id_test, DCI_Info = dci_info,  : 
  (converted from warning) Table parameter with path_id 5738 does not exist for specified parameter type variable
 done successfully.

Executing test function test.CheckParameterInSimulationNoneVariables  ... Timing stopped at: 0 0 0
Error in getSpeciesInitialValue(path_id = path_id_test, DCI_Info = dci_info,  : 
  (converted from warning) Table parameter with path_id 134 does not exist for specified parameter type variable
 done successfully.

Executing test function test.SetSimulationTimePointsAndSimulate  ... Timing stopped at: 0.13 0 0.13
Error in processSimulation(DCI_Info = dci_info) : 
  Unknown interval distribution type passed: 
 done successfully.

```
etc..

**Comment by msevestre** [comment]
see attached protocol
[Protocol.zip](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/2236184/Protocol.zip)

**Comment by PavelBal** [comment]
@msevestre Yes, these are known issues and all reported. Some I can work on, some are probably in DCI (resp. DCIR, e.g. https://github.com/Open-Systems-Pharmacology/R-Toolbox/issues/10) and they are still not "open source"...
