### ISSUE TITLE
getParameter() stops when the given parameter is not found

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#41]
The behavior of getParameter() (and also of getTableParameter()) is that it stops when the provided parameter is not found, interrupting the code. This is OK and should be managed by try-catch construct when the user searches for a parameter.

First problem:The try-catch hint should be placed to the documentation of the method - does R documentation has an extra block for the exceptions/errors the method can produce?

Second problem: No user probably knows of this behavior, because getParameter() ALWAYS returned something, even if the parameter is not in the simulation (or not for the specific type). In that case, the output was

```
$Value
numeric(0)

$Index
[1] 0
```

and everything happily proceeded with this output. Now that this is fixed and getParameter() behaves like it was supposed to behave (stopping when the parameter is not found), the users would be surprised to see their code "broken".

Third problem: Searching for all parameters, e.g., by `getParameter("*", list(Type="variable"), DCI_Info = myDCI)` can also cause errors. Instead, the method getParameterStatus should be used.

So this "new - old" behavior should be mentioned in the next release notes.

OR: whe change the behavior of getParameter/getTableParameter/getSpeciesInitialValue in that way that it ALWAYS will return a list with the columns "value" and "Index". If the given parameter is not found, the lenght of this list would be zero. Additionally, a warning message is to be displayed.

**Comment by msevestre** [comment]
>change the behavior of getParameter/getTableParameter/getSpeciesInitialValue in that way that it ALWAYS will return a list with the columns "value" and "Index". If the given parameter is not found, the lenght of this list would be zero. Additionally, a warning message is to be displayed.

I like this idea. I am not sure if this is done often in R, but I like in general to ensure in the code that the caller of a method does not have to worry about "NULL" or "invalid" etc... returned for a method. 

The caller does not have to worry about edge cases and can continue on as usual. This kind of reflects your proposal I guess?

**Comment by PavelBal** [comment]
> The caller does not have to worry about edge cases and can continue on as usual. This kind of reflects your proposal I guess?

Well, the caller still has to check if the returned list is not empty (simply because the parameter isn't there) before working on it, but otherwise yes, the methods would always return a valid output.

**Comment by msevestre** [comment]
Sure. But it's either empty or not empty...not another state that the caller has to worry about.

I like that. I think that not having the fear of NULL as I call it  simplifies the code greatly.
