### ISSUE TITLE
new function request: setScaleDivisorsAfterSim()

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/R-Toolbox#43]
As name says, I would like to write a function, that calculates and then sets the scale divisors as you can do within MoBi after you have run a simulation.
For this, I have a few questions, as my first tries failed (DCI_Info got corrupted and simulation failed), maybe someone (@msevestre, @Yuri05 ?) can help:

1. How is the divisor calculated in MoBi. From looking at the values it may be the geometric mean? Correct?
2. Now, I have to know, where to write the value in the DCI_Info: from looking at the DCI_Info, there are a number of places: 
a. DCI_Info$InputTab$AllSpecies$ScaleFactor
b. DCI_Info$InputTab$VariableSpecies$ScaleFactor
c. DCI_Info$ReferenceTab$AllSpecies$ScaleFactor
d. DCI_Info$ReferenceTab$VariableSpecies$ScaleFactor

Do I have to write them anywhere else? and...
3. are there any exceptions to the rule..i.e. do you skip any special species when setting the divisor (maybe Lumen, or EndosomalClearance)

Any help appreciated,
thanks, Stephan

**Comment by PavelBal** [comment]
Just a warning - applying MoBi calculated scale divisors sometimes renders my model unsolvable.

**Comment by Yuri05** [comment]
>How is the divisor calculated in MoBi. From looking at the values it may be the geometric mean? Correct?

check the code [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/36b61a1dc184a671b3b45a0043203342edeae15b/src/OSPSuite.Core/Domain/Services/ScaleDivisorCalculator.cs#L179)

>Now, I have to know, where to write the value in the DCI_Info: from looking at the DCI_Info, there are a number of places:
a. DCI_Info$InputTab$AllSpecies$ScaleFactor
b. DCI_Info$InputTab$VariableSpecies$ScaleFactor
c. DCI_Info$ReferenceTab$AllSpecies$ScaleFactor
d. DCI_Info$ReferenceTab$VariableSpecies$ScaleFactor

DCI_Info$InputTab$**_VariableSpecies_**$ScaleFactor
You can set scale factor only for those species which were set as variable in _initSimulation_.

>3. are there any exceptions to the rule..i.e. do you skip any special species when setting the divisor (maybe Lumen, or EndosomalClearance)

Not sure what you mean. Scale Divisor can be calculated and set for any state variable of the system.

**Comment by StephanSchaller** [comment]
`Math.Pow(10, values.ConvertToLog10Array().ArithmeticMean())` this should be the geometric mean, but it's then [rounded ](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/36b61a1dc184a671b3b45a0043203342edeae15b/src/OSPSuite.Core/Domain/Services/ScaleDivisorCalculator.cs#L34) to the next (smaller) exponent.

> You can set scale factor only for those species which were set as variable in `initSimulation`.

Actually, when browsing the code I just now realized ScaleDivisors can be set with setSpeciesInitialValue:
`setSpeciesInitialValue(0,'*',1,'parameterType','reference','property','ScaleFactor');` 
(MATLAB TB, although not sure why the example given in the function descriptions sets the value to zero!!? Would the simulation even run then?)
```
dci_info <- setSpeciesInitialValue(value = 2, 
  path_id = 134, 
  options = list(Type = "variable", Property = "ScaleFactor"), 
  DCI_Info = dci_info)
```
(R Toolbox), BUT you can also set `Type = "reference"`  (not quite grasped the concept of the ReferenceTab, can you quickly explain that?)

> Not sure what you mean. Scale Divisor can be calculated and set for any state variable of the system.

Yes, can, but I was just wondering if it would make sense to NOT scale e.g. Species in LUMEN when no oral administration is set (concentrations in LUMEN are then very small) and leave them at 1 because typically, when oral drugs are given LUMINAL concentrations are quite high...
But it seems there are no special cases in the code...

For the different terms used in Toolbox Code and the Data Structure (DCI_Info): once it's "Divisor", and once it's "Factor". But actually it is always used/handled as a divisor, right?

**Comment by StephanSchaller** [comment]
@PavelBal 

> Just a warning - applying MoBi calculated scale divisors sometimes renders my model unsolvable.

And how exactly are you setting these values?

**Comment by PavelBal** [comment]
I mean, IN MoBi, with the "Calculate Scale Divisor"-button.

2018-01-30 12:59 GMT+01:00 esqlabs GmbH <notifications@github.com>:

**Comment by StephanSchaller** [comment]
Yes, I realized too late you were talking about MoBi, not the Toolbox...(which is why I deleted the question reight after I realized that) ;-)

The simulation crashing when setting Scale Factors? this is definitely not intended... Do you also change solver accuracy?
Why do you think this happens?
--> should this be reported as a bug ?

**Comment by PavelBal** [comment]
> Do you also change solver accuracy?

No (it was a long time ago). The intension of scale factors is to increase the possible solver tolerances, and not the other way around :)

> Why do you think this happens?

Could be because of some species resulted in negative concentrations? That time, the check for amount >= 0 was not implemented, and due to numerical noise, active transport processes did produce "negative" amounts.

**Comment by msevestre** [comment]
@StephanSchaller 
>Math.Pow(10, values.ConvertToLog10Array().ArithmeticMean()) this should be the geometric mean

Why geometric mean? The values are already on a log10 scale.

**Comment by Yuri05** [comment]
>(MATLAB TB, although not sure why the example given in the function descriptions sets the value to zero!!? Would the simulation even run then?)

No, it would produce an exception latest during [setting the scale value](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/12d6a23cde8da8a76e3e7737d069b5ff3ae77ccb/src/OSPSuite.SimModel/src/Species.cpp#L55)
Seems those examples are not run very often :-)

>Yes, can, but I was just wondering if it would make sense to NOT scale e.g. Species in LUMEN when no oral administration is set (concentrations in LUMEN are then very small) and leave them at 1 because typically, when oral drugs are given LUMINAL concentrations are quite high...
But it seems there are no special cases in the code...

Right, there are no special cases. It's up to the modeler to decide if some state variable should be scaled.

>For the different terms used in Toolbox Code and the Data Structure (DCI_Info): once it's "Divisor", and once it's "Factor". But actually it is always used/handled as a divisor, right?

That's correct.

**Comment by StephanSchaller** [comment]
> Why geometric mean? The values are already on a log10 scale.

The geometric mean can also be expressed as the exponential of the arithmetic mean of logarithms. See [here](https://en.wikipedia.org/wiki/Geometric_mean#Relationship_with_logarithms). And this looks like exactly what ist stated above (I don't really know how to read C# mat expressions).

**Comment by msevestre** [comment]
Geometric mean used ln (log base e). This is using log10 (log base 10). So all in all not really the same.
I think the code above is correct

**Comment by StephanSchaller** [comment]
@PavelBal 

>  That time, the check for amount >= 0 was not implemented

Well, if you think that solved the issue, why the warning? ;-)

**Comment by StephanSchaller** [comment]
> Geometric mean used ln (log base e). This is using log10 (log base 10). So all in all not really the same.
I think the code above is correct

This transformation can be  done with any base (it's "base-independent", see here [logarithmic identities](https://en.wikipedia.org/wiki/List_of_logarithmic_identities))

**Comment by Yuri05** [comment]
>I think the code above is correct

It is :smile:  Log base does not matter.

**Comment by msevestre** [comment]
Excellent. So the code above is correct and there is no need to change anything. Perfect :)

**Comment by StephanSchaller** [comment]
> ... and there is no need to change anything

😄 ...was never my intention.

I just didn't know there already was an option to set ScaleDivisors in `setSpeciesInitialValue
` and then I was just interested in how the values were actually calculated in MoBi (as I was sure you already put some thought into it) so I can use same formula in my script.

But as there is no function for everybody to calculate the scaleDivisors, maybe we instead implement sth. to automatically **calculate AND** set the divisors (like in MoBi).

**Comment by PavelBal** [comment]
> Well, if you think that solved the issue, why the warning? ;-)

@StephanSchaller Because I _think_ that it solved, I do not _know_ it ;)

**Comment by StephanSchaller** [comment]
Now, I have tried for a long time, but I do not manage to get the scale factors to work via the toolbox...

I have generated a simple Simulation (IV dose, protein model) and then sent it to MoBi to set scale divisors. The Simulation with set scale divisors was then exported as .xml.

Then I tried setting the scale factors again and compare simulation results. My own calculates scale factors were slightly different, than the ones set in Moby, but ALSO the simulation results were different. 
The latter should not be the case.
I also tried setting all scale factors to "1". The results are totally different then.

Here is my code, can you please tell me what went wrong?

```
xml <- "./GIMHum_TestScaleFactors.xml"

initStruct <- list()
initStruct <- initSpeciesInitialValue(initStruct,"*", initializeIfFormula = "always")
DCI_Info <- initSimulation(xml,initStruct)
# parameterStatus <- getParameterStatus(DCI_Info = DCI_Info)
DCI_Info <- processSimulation(DCI_Info = DCI_Info)

existenceInfo <- existsSpeciesInitialValue("*", DCI_Info = DCI_Info)
# We copy the DCI to "clone the simulation
DCI_Info2 <- DCI_Info
SIM_Info <- {}

# Now we scale:
# Loop over all Species
for (iSpec in 1:length(existenceInfo$Index)){
  # Get Simulation results
  SIM_Info$spec_values[[iSpec]] <- getSimulationResult(options = list(Index=existenceInfo$Index[[iSpec]]), DCI_Info = DCI_Info2)[,2]
  # Calculate geometric mean (only for nonzero and positive simulation results) and round to nearest decimal
  SIM_Info$GeoMeanV[[iSpec]] <- 10^round(log10(exp(sum(log(SIM_Info$spec_values[[iSpec]][SIM_Info$spec_values[[iSpec]] > 0]), na.rm=TRUE) / length(SIM_Info$spec_values[[iSpec]]))))
  if (SIM_Info$GeoMeanV[[iSpec]] <= 0){
    # Set to ONE if GeoMean is <= 0 (maybe thi is already cought above when only taking positive Sim-results)
    SIM_Info$GeoMeanV[[iSpec]] <- 1
  }
  # Now we only want actual Species (no Species within administration protocols)
  if (grepl("Organism", existenceInfo$Path[iSpec], fixed = TRUE)){
    #  some special cases excluded, if Lumen is not excluded, simulation will even crash
    if (!grepl("Lumen", existenceInfo$Path[iSpec], fixed = TRUE)){
      DCI_Info2 <- setSpeciesInitialValue(SIM_Info$GeoMeanV[[iSpec]], options = list(Type = "variable", Property = "ScaleFactor", Index=existenceInfo$Index[[iSpec]]), DCI_Info = DCI_Info2)
    }
  }
}

# ALTERNATIVELY I have written a quick routine to write directly into DCI_Info (you have to source file first)
# DCI_Info2 <- setScalingFactorsAfterSim(DCI_Info = DCI_Info)

#  This is to check if ScaleFactors before/after are the same (not the case, but almost all are)
facsSF <- DCI_Info$InputTab$VariableSpecies$ScaleFactor/DCI_Info2$InputTab$VariableSpecies$ScaleFactor
NotOne <- which(facsSF!=1)
for (ii in 1:length(NotOne)){
print(DCI_Info$InputTab$VariableSpecies$Path[NotOne[ii]])
SIM_Info$diff_spec_values[[NotOne[ii]]] <- getSimulationResult(options = list(Index=existenceInfo$Index[[NotOne[ii]]]), DCI_Info = DCI_Info2)[,2]
# I used following line to write the oldvalues back to see if simulation results will then be identical again (results are then indeed identical again)
# DCI_Info2 <- setSpeciesInitialValue(DCI_Info$InputTab$VariableSpecies$ScaleFactor[NotOne[ii]], options = list(Type = "variable", Property = "ScaleFactor", Index=existenceInfo$Index[[NotOne[ii]]]), DCI_Info = DCI_Info2)
}

# Visual representations of scale factor differences (before/after)
ggplot() + geom_col(aes(x=c(1:length(facsSF)),y=facsSF))#+ scale_y_continuous(trans="log10")

# Now plot simulation results for simulation with original and newly set scale factors
Values <- getSimulationResult("*|Organism|PeripheralVenousBlood|Insulin|Plasma \\(Peripheral Venous Blood\\)",DCI_Info=DCI_Info)
plot(Values,type="l")

# Get results for simulation with newly set factors
DCI_Info2 <- processSimulation(DCI_Info = DCI_Info2)

Values <- getSimulationResult("*|Organism|PeripheralVenousBlood|Insulin|Plasma \\(Peripheral Venous Blood\\)",DCI_Info=DCI_Info2)
plot(Values,type="l")

# for me, results are NOT the same!!!
```

**Comment by StephanSchaller** [comment]
Just so you have an Idea of how different the simulation is with the original Scale Divisors set in Mobi:
![image](https://user-images.githubusercontent.com/25477643/35590781-2a33e51a-0608-11e8-9944-b6cc56b086eb.png)

Compared to the simulation when I reset all scale divisors to "1" in R:
![image](https://user-images.githubusercontent.com/25477643/35590775-217398b2-0608-11e8-9e99-513e44b18dbe.png)

**Comment by msevestre** [comment]
@StephanSchaller Hard for me to tell because I am not familiar with the R code in the toolbox at all. 
Are you sure that the `setSpeciesInitialValue` is actually doing what you expect?


Can you try it on a much smaller model (one compartment, few species) and see if you have the same issues?

if that works, can you try with a standard PKSim Model (Small moelcule model) and not the protein model. What's the status there?

**Comment by StephanSchaller** [comment]
@msevestre 
Well, `setSpeciesInitialValue` sets scale divisors for "variableSpecies" only. But it does this as expected.

But after trying everything out, I have a feeling that the error may be somewhere deeper and the scale divisors, when the simulation is exported to xml, may be multiplied into some property that's later not dependent on the scaleFactor in the DCI_Info... I don't know...

Can you trace, 
1. where scale divisors are applied to in the simulation in MoBi
2. how and where scale divisors are trensferred to when an xml-structure is generated?

**Comment by msevestre** [comment]
It's all in the XML. MoBi just writes the xml but never interacts with it
after the fact. MoBi does not use DCI either

What's a variable species? A species with a RHS?

**Comment by StephanSchaller** [comment]
> MoBi just writes the xml but never interacts with it

Yes I know, which is why I thought that it either happens when the divisors are set within MoBi (unlikely) or when R reads the xml into the DCI_Info data.frame... just thoughts where sth. might be going wrong...

> What's a variable species? A species with a RHS?

No, that's a species you specifiy to be initialized and thus it's "tagged" as "variable" so you can change it later.

**Comment by PavelBal** [comment]
I am not comfortable with being forced to initialize a species (set is variable) for applying a scaling factor. Initializing a species my destroy its formula, which is OK when the _initial value_ of the species must be changed, but not when only the scale factor is adjusted. Can this be done?

**Comment by Yuri05** [comment]
>I am not comfortable with being forced to initialize a species (set is variable) for applying a scaling factor. Initializing a species my destroy its formula, which is OK when the initial value of the species must be changed, but not when only the scale factor is adjusted. Can this be done?

Everything _can_ be done. Please create an issue.

**Comment by Yuri05** [comment]
>But after trying everything out, I have a feeling that the error may be somewhere deeper and the scale divisors, when the simulation is exported to xml, may be multiplied into some property that's later not dependent on the scaleFactor in the DCI_Info... I don't know...

If you try to set ALL species and/or ALL parameters as variable - your simulation will in general produce wrong results. So please follow the suggestion by @msevestre 
>Can you try it on a much smaller model (one compartment, few species) and see if you have the same issues?
if that works, can you try with a standard PKSim Model (Small moelcule model) and not the protein model. What's the status there?
