### ISSUE TITLE
Confusion about parameters, species, and their types in the DCI

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#46]
[QC_R.zip](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/1681390/QC_R.zip)

I am really confused about the concept of what is a parameter, what is a species, and what types they may have.

Consider the attached test model created in MoBi. It is a simple model with one compartment "Organism" and two molecules. No reactions or processes are defined.

There are three parameters of the compartment "Organism":
1) "constantParam" with a constant value "0".
2) "RHS_Param_constantInit", a state variable with a constant initial value "0"
3) "RHS_Param_formulaInit", a state variable with the initial value defined by the formula "5+6".

There are two molecules:
1) "myMolecule_constant" with the constant start value "0"
2) "myMolecule_formula" with the start value defined by the formula "0".

The exported XML is also attached.

Now, loading this simulation in R.

```
library(MoBiToolboxForR, quietly=TRUE)

testXML = ".\\QC_R\\testSim.xml"
DCI_Info_test <- initSimulation(testXML, whichInitParam = "none")
```

**Question 1**: DCI_Info_test has the lists "InputTab" and "ReferenceTab". What do they mean?

The lists in the "InputTab":
1) AllParameters: 

```
> DCI_Info_test[["InputTab"]][["AllParameters"]][["Path"]]
 [1] "testSim|Organism|Volume"                            "testSim|Organism|constantParam"                    
 [3] "testSim|Organism|myMolecule_constant"               "testSim|Organism|myMolecule_constant|Concentration"
 [5] "testSim|Organism|myMolecule_formula"                "testSim|Organism|myMolecule_formula|Concentration" 
 [7] "AbsTol"                                             "RelTol"                                            
 [9] "H0"                                                 "HMin"                                              
[11] "HMax"                                               "MxStep"                                            
[13] "UseJacobian"                                       
attr(,"Name")
[1] "Path"
attr(,"Description")
[1] ""
```

**Question 2**: Why are the values of "testSim|Organism|myMolecule_constant" and "testSim|Organism|myMolecule_formula" included in the "AllParameters" list? They are species and not parameters, right? Even if the "species" were optimized to "Parameters" because they are constant (no transport processes, no reactions), it is veeeery confusion for the user, because I would expect to find my molecules under "species".

2) AllSpecies:
```

> DCI_Info_test[["InputTab"]][["AllSpecies"]][["Path"]]
[1] "testSim|Organism|RHS_Param_constantInit" "testSim|Organism|RHS_Param_formulaInit" 
attr(,"Name")
[1] "Path"
attr(,"Description")
[1] ""
```

This time, species turned into parameters! OK, I got the concept of "state variables" being actually species and not parameters, but only because I asked @Yuri05 once.

And while the concept that a state variable is not a parameter but a species can be accepted (but not without proper documentation!!!), the other way around is a no-go, because the user cannot know, when a species (e.g., a modeled molecule) will turn into parameter!

**Question 3:** What do the types "VARIABLE", "READONLY", "CURRENT", "REFERENCE", mean?

**Question 4:** If a species (or a parameter) is initialized, it will appear in the list `DCI_Info_test$InputTab$VariableSpecies`, but still be also listed in `DCI_Info_test$InputTab$AllSpecies`.  What happens, if any value is changed in VariableSpecies, but not in AllSpecies, or the other way around?

**Comment by Yuri05** [comment]
>Question 2: Why are the values of "testSim|Organism|myMolecule_constant" and "testSim|Organism|myMolecule_formula" included in the "AllParameters" list? They are species and not parameters, right? Even if the "species" were optimized to "Parameters" because they are constant (no transport processes, no reactions), it is veeeery confusion for the user, because I would expect to find my molecules under "species".

That's correct: species (molecule amounts) which are obviously constant during simulation are transformed into parameters during [xml export process](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/bdedf8acded03ba1a1279c2e1ada6c58d321e6b3/src/OSPSuite.Core/Serialization/SimModel/Services/CreateExportModelVisitor.cs#L151). While it simplifies analysis and speed optimization of the final model, indeed it might be confusing for the user. Maybe this behavior should be changed - to be discussed. On the other hand, in the most cases users are not interested in the constant species. 

>Question 4: If a species (or a parameter) is initialized, it will appear in the list DCI_Info_test$InputTab$VariableSpecies, but still be also listed in DCI_Info_test$InputTab$AllSpecies. What happens, if any value is changed in VariableSpecies, but not in AllSpecies, or the other way around?

If a species or a parameter is not varied user still might be interested in its (initial) value. For this reason, both variable and non-variable species and parameters are stored in **AllXXX**-Table.
Changing any values in **AllXXX**-Tables has no influence on the simulation (those tables are meant as readonly.).
Changing any value in **VariableXXX**-Table will update this value and all dependent value in **AllXXX**-Table**s** (currently this update only happens after `RunSimulation`)

>Question 1: DCI_Info_test has the lists "InputTab" and "ReferenceTab". What do they mean?
>Question 3: What do the types "VARIABLE", "READONLY", "CURRENT", "REFERENCE", mean?

S. OSP Suite manual (**43.4. Manipulate parameters**) (which explains everything except **CURRENT**. Regarding this one I also have no idea)

**Comment by Yuri05** [comment]
@PavelBal  I think CURRENT in this context is the same as VARIABLE. Or can you point out where this is not the case?

**Comment by PavelBal** [comment]
Thank you @Yuri05 !

> I think CURRENT in this context is the same as VARIABLE. Or can you point out where this is not the case?

https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/9d8655dbea3106011c93d986e414e2d159ab2476/src/code/getParameter.R#L61-L66

Looks like it is more than "Variable"..

**Comment by Yuri05** [comment]
well... maybe @KatrinCoboeken knows the answer.

**Comment by StephanSchaller** [comment]
REFERENCE:

OSPS manual: "For every variable parameter a reference parameter exists. Variable parameters can be set relative to this reference parameter. The values of reference parameter can be varied. "

Maybe this explanation should be made more clear. 
Also `setParameter` has no further description about how this can/should be used.

@KatrinCoboeken ?

**Comment by KatrinCoboeken** [comment]
I can tell you what the parameter type in the matlab toolbox means, but I have no experience in R. 
I the Matlab toolbox current is used if you do not want to specify if the parameter is variable or readonly.
The function getParameter searches first for a 'variable' parameter, if no 'variable' parameter is found, the readonly table is searched.
I would advise whenever possible to select variable or readonly instead of current.

**Comment by StephanSchaller** [comment]
@KatrinCoboeken but what about the "reference" type?

**Comment by KatrinCoboeken** [comment]
For each variable parameter exist a reference parameter. The initialsisation sets the values of the reference parameters equal to the values of the variable  parameters. The reference parameter is used by the function setRelativeParameter. This function sets the value of the variable Parameter relative to the value of the reference Parameter. If you need another reference yo can Change the reference value with the function setParameter using parametertype 'Reference'.
The same concept holds for species Initial values.
