### ISSUE TITLE
"IsFormula" is stored in the DCI_Info not correctly

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#47]
Consider my example from #46 .

The described model is loaded into R and no parameters are initialized:
```
library(MoBiToolboxForR, quietly=TRUE)

testXML = ".\\QC_R\\testSim.xml"
DCI_Info_test <- initSimulation(testXML, whichInitParam = "none")
```

Now I want to initialized all species that are NOT formulas. For this, I first get all the species (which turn out  to be parameters, and I am getting no species at all, but this is another story described in #46 ...), and iterate through the list while getting the property "IsFormula". If the species in not a formula, I initialize its initial value:

```
allSpecies = getSpeciesInitialValue(path_id ="*", list(Type = "readonly"), DCI_Info = DCI_Info_test);
initStruct <- list()
for (idx in allSpecies$Index){
  isFormula = getSpeciesInitialValue(path_id ="*", list(Type = "readonly", Property = "IsFormula", Index = idx), DCI_Info=DCI_Info_test)$Value;
  if (!isFormula){
    path_id = getSpeciesInitialValue(path_id ="*", list(Type = "readonly", Property = "Path", Index = idx), DCI_Info=DCI_Info_test)$Value;
    initStruct <- initSpeciesInitialValue(initStruct, path_id, initializeIfFormula = "never")
  }
}
```

Init struct now consists of two parameters (state variables), one of which was defined by a formula:

```
initStruct[["InitialValues"]][["Path_ID"]]
        [,1]                                     
        "testSim|Organism|RHS_Param_constantInit"
path_id "testSim|Organism|RHS_Param_formulaInit" 
```

Now we could think that the formula of "RHS_Param_formulaInit" was optimized to a constant, because it was just "5+6", and everything is fine. Well, it is not, because trying to initialized the model with this init struct leads to an error!

```
> DCI_Info_test <- initSimulation(testXML, ParamList = initStruct)
Error in initParameterStruct(ParamList, TableArray[[id]], id, DCI_Info) : 
  The SpeciesInitialValue is defined as Formula:  If you want to inititalize this species initial value do not use option 'never' for the function initParameter testSim|Organism|RHS_Param_formulaInit 5+6
```

Looking at DCI_Info, nether the parameters nor the Species lists have their "isFormula" set to 1 for any of the species/parameters!

```
> DCI_Info_test[["InputTab"]][["AllParameters"]][["Formula"]]
 [1] "" "" "" "" "" "" "" "" "" "" "" "" ""
attr(,"Name")
[1] "Formula"
attr(,"Description")
[1] ""

> DCI_Info_test[["InputTab"]][["AllSpecies"]][["IsFormula"]]
[1] 0 0
attr(,"MinValue")
[1] 0
attr(,"MaxValue")
[1] 0
attr(,"DefaultValue")
[1] 0
attr(,"Name")
[1] "IsFormula"
attr(,"Description")
[1] ""
```

**Comment by Yuri05** [comment]
>Looking at DCI_Info, nether the parameters nor the Species lists have their "isFormula" set to 1 for any of the species/parameters!

This is correct behavior. What happens here: 
* At the beginning, 2 parameters (concentrations) and 1 species (`RHS_Param_formulaInit`) have formulas. Trying to set one of them as variable at the beginning leads to the error/warning you described (`The SpeciesInitialValue is defined as Formula`)
<img width="697" alt="aufnahme22" src="https://user-images.githubusercontent.com/25061876/35628147-e7606db8-0692-11e8-9f75-3dab38680f0d.png">

* However, if you initialize a simulation without setting any parameter/species as variable, all those formulas are replaced by constant values (`5+6` trivially, concentrations due to the fact that all molecule amounts and all volumes are const during the simulation). Thus after the initialization there are indeed no more formulas in your model.
<img width="622" alt="aufnahme23" src="https://user-images.githubusercontent.com/25061876/35628330-7c271528-0693-11e8-9eee-f90c3ef6ae3d.png">

**Comment by PavelBal** [comment]
I do not get it. How can I then initialize all parameters/species except those with formulas?

**Comment by Yuri05** [comment]
In the Matlab-Toolbox you can do it with [`allNonFormula`](https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox-Core/blob/be5e39f109d4625fef6985a17e395d80655ac0d2/code/initSimulation.m#L11)
~~This can be done in the same manner in the R-Toolbox (if not implemented yet).~~
And as far as I see it's also [implemented in R](https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/9d8655dbea3106011c93d986e414e2d159ab2476/src/code/initSimulation.R#L82)

**Comment by PavelBal** [comment]
That does not work for species, only for parameters!

```
>DCI_Info_test <- initSimulation(testXML, whichInitParam = "all")
>DCI_Info_test$InputTab$VariableSpecies$Path
[1] "testSim|Organism|RHS_Param_constantInit" "testSim|Organism|RHS_Param_formulaInit" 
attr(,"Name")
[1] "Path"
attr(,"Description")
[1] ""
```

Initializing all creates two variable species. Initializing "allNonFormula" creates NO variable species, although at least "testSim|Organism|RHS_Param_constantInit" should be there.

> DCI_Info_test <- initSimulation(testXML, whichInitParam = "allNonFormula")
> DCI_Info_test$InputTab$VariableSpecies$Path
character(0)
attr(,"Name")
[1] "Path"
attr(,"Description")
[1] ""

The ouput is also emtpy for a PBPK-Model exported from PK-Sim, so it is not because of "optimization" or whatever.

**Comment by Yuri05** [comment]
Might be a bug in the R-Toolbox. Please create an issue for that.

Initializing your model in Matlab with `allNonFormula `sets _RHS_Param_constantInit_ species to variable.
Means: if we have an issue here, it's in [initSimulation.R](https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/develop/src/code/initSimulation.R)
