### ISSUE TITLE
R Toolbox - Release > 7.0.0 fail to return output table

### ISSUE THREAD

**Issue by CandideThunder** [Open-Systems-Pharmacology/R-Toolbox#5]
`getSimulationResults `returns per column only one value, the remaining are NA
It can be shown, that the call to `RDCI_GetOutputTable` in the DLL is returning differently compared to relase 6.3.2.

The attached example code prints a vector of number with 6.3.2 (rightly), but a single number with 7.0.0 or 7.1.0

[miniExampleToDemoToolboxBug.zip](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/892965/miniExampleToDemoToolboxBug.zip)
[testSim.zip](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/892966/testSim.zip)

**Comment by Yuri05** [comment]
Fixed

**Comment by Yuri05** [comment]
Not really fixed

**Comment by Yuri05** [comment]
Fixed in the current version
