### ISSUE TITLE
Add "skip" property to initializeIfFormula in initiParameter/initSpeciesInitialValue

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#51]
During initialization of parameters/species, the onces defined by the formula can be handeled differently. For this, the functions "initParameter" and "initSpeciesInitialValue" have an argument "initializeIfFormula" with three possible states:

"never": If the parameter is a formula, initSimulation() will produce an error
"always": If the parameter is a formula, initSimulation() will silently succeed
"withWarning": The parameter will be initialized, but a warning will be displayed.

What I miss is another option:
"skip": the parameter will be not initialized, but initSimulation() will still succeed.

Possible use case - I have two version of a model with a certain parameter "X". In one model, "X" is a constant, in another it is a formula. In R-code, I only want to initialize "X" if it is constant. WIth having the "skip" option, I coud use the same code for the both models.

**Comment by PavelBal** [comment]
Will take a look at it.

**Comment by StephanSchaller** [comment]
> "skip": the parameter will be not initialized, but initSimulation() will still succeed.

Yes, I implemented the same for myself in the MATLAB TB once.
Let's also give out a warning if a Parameter is skipped "skipWithWarning"

**Comment by PavelBal** [comment]
Will do.
