### ISSUE TITLE
RDCI does not update scaling factors, results erroneous

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#52]
Originating from #43 It seems that RDCI ignores/messes up the scale factors if they are changed after initSimulation().

Two simulations exported from MoBi which are identical except for the scaling factors - "xml_one" with all scaling factors == 1, and xml_nonOne with scaling factors calculated in MoBi.

1) Initialize xml_one, set all species initial values to variable, and simulate:

```
#Initialize a simulation with scale factors == 1.
xml_one <- "D:\\Work\\QSP_Diabetes_Platform\\Toolbox\\QC_R\\GIMHum_TestScaleFactors_1.xml"
DCI_Info_one <- initSimulation(xml_one, whichInitParam = "none")
allSpecies = getSpeciesInitialValue(path_id ="*", list(Type = "readonly"), DCI_Info = DCI_Info_one);
initStruct <- list()
for (idx in allSpecies$Index){
  path_id = getSpeciesInitialValue(path_id ="*", list(Type = "readonly", Property = "Path", Index = idx), DCI_Info=DCI_Info_one)$Value;
  initStruct <- initSpeciesInitialValue(initStruct, path_id, initializeIfFormula = "always")
}
DCI_Info_one = initSimulation(xml_one, ParamList = initStruct);
#Process sim one
DCI_Info_one <- processSimulation(DCI_Info = DCI_Info_one)
```

2) Initialize "xml_nonOne" and set all species initial values to variable:

```
#Initialize a simulation with scale factors != 1.
xml_nonOne <- "D:\\Work\\QSP_Diabetes_Platform\\Toolbox\\QC_R\\GIMHum_TestScaleFactors.xml"
DCI_Info_nonOne <- initSimulation(xml_nonOne, whichInitParam = "none")
allSpecies = getSpeciesInitialValue(path_id ="*", list(Type = "readonly"), DCI_Info = DCI_Info_nonOne);
initStruct <- list()
for (idx in allSpecies$Index){
  path_id = getSpeciesInitialValue(path_id ="*", list(Type = "readonly", Property = "Path", Index = idx), DCI_Info=DCI_Info_nonOne)$Value;
  initStruct <- initSpeciesInitialValue(initStruct, path_id, initializeIfFormula = "always")
}
DCI_Info_nonOne = initSimulation(xml_nonOne, ParamList = initStruct);
```

3) Set all scaling factors to 1 (I am doing it in all DCI table to compare the DCIs):

```
#Set all scale factors to 1
for (idx in 1 : length(DCI_Info_nonOne$InputTab$AllSpecies$ScaleFactor)){
  DCI_Info_nonOne$InputTab$AllSpecies$ScaleFactor[idx] = 1;
}
for (idx in 1 : length(DCI_Info_nonOne$InputTab$VariableSpecies$ScaleFactor)){
  DCI_Info_nonOne$InputTab$VariableSpecies$ScaleFactor[idx] = 1;
}
#
for (idx in 1 : length(DCI_Info_nonOne$ReferenceTab$AllSpecies$ScaleFactor)){
  DCI_Info_nonOne$ReferenceTab$AllSpecies$ScaleFactor[idx] = 1;
}
for (idx in 1 : length(DCI_Info_nonOne$ReferenceTab$VariableSpecies$ScaleFactor)){
  DCI_Info_nonOne$ReferenceTab$VariableSpecies$ScaleFactor[idx] = 1;
}
```

Input and reference tables are now identical between xml_one and xml_nonOne:

```
> all.equal(DCI_Info_one$InputTab, DCI_Info_nonOne$InputTab)
[1] TRUE
> all.equal(DCI_Info_one$ReferenceTab, DCI_Info_nonOne$ReferenceTab)
[1] TRUE
```

4) Simulate xml_nonOne:

`DCI_Info_nonOne <- processSimulation(DCI_Info = DCI_Info_nonOne)`

Scaling factors in the InputTab$AllSpecies are reset!

```
> all.equal(DCI_Info_one$InputTab, DCI_Info_nonOne$InputTab)
[1] "Component “AllSpecies”: Component “ScaleFactor”: Mean relative difference: 2.259764"
> all.equal(DCI_Info_one$ReferenceTab, DCI_Info_nonOne$ReferenceTab)
[1] TRUE
```

This happens here 
https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/9d8655dbea3106011c93d986e414e2d159ab2476/src/code/processSimulation.R#L12-L20

As pointed out in #43 , the results are completely different, too!

**Comment by msevestre** [comment]
I'd like @Yuri05 to look into that to ensure that there is no issue with the SimModelComp component at that stage

**Comment by StephanSchaller** [comment]
Alright, we need to get this going, as the R-Toolbox is getting popular and ScaleDivisors are a very important feature for more complex models.
@Yuri05, how should we proceed. How can we help?

**Comment by Yuri05** [comment]
@StephanSchaller Could you create an analogon of your R code for reproducing the behavior in **Matlab** and upload it along with the (xml-)model?

**Comment by StephanSchaller** [comment]
Now, I have the following:
Two xmls created from the same simulation (.mbp3 file included): once with SF left at default (=1, file ...SFis1.xm, xml1 in script) and once I set the SFs in MoBi (the other xml file, xml2 in script).

In the script I now simulate results for both files and for third run I reset the scale factors set in MoBi for xml2 back to 1 an then run the simulation. Comparing the simulations gives this result:

![image](https://user-images.githubusercontent.com/25477643/36787995-8dbf767c-1c8c-11e8-88e7-57dfd9e08b4e.png)

You can see, that the simulation is total crap for the reset scale factors...
[GIMHum_TestScaleFactors.zip](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/1767079/GIMHum_TestScaleFactors.zip)

attached the files in a zip-file

As I do not have MATLAB, I cannot give you the same for MATLAB

**Comment by PavelBal** [comment]
@StephanSchaller Does this script actually work for you? I always get the error 
```
 Error in updateSimulationInputs(DCI_Info) : 
  Component handle 258639328 is invalid! 
```

when two simulations are initilized consequentially without being run in between. So your code:

```
DCI1 <- initSimulation(xml1,initStruct)
DCI2 <- initSimulation(xml2,initStruct)
# run the original simulations
DCI1 <- processSimulation(DCI_Info = DCI1)
DCI2 <- processSimulation(DCI_Info = DCI2)
```

ends up in the error, while 

```
DCI1 <- initSimulation(xml1,initStruct)
DCI1 <- processSimulation(DCI_Info = DCI1)

DCI2 <- initSimulation(xml2,initStruct)
DCI2 <- processSimulation(DCI_Info = DCI2)
```

works (with the released toolbox).

**Comment by StephanSchaller** [comment]
> @StephanSchaller Does this script actually work for you? I always get the error

Kann ich bestätigen. Hab das Skript manuell durchgearbeitet. Kann sein, dass ich zufällig die Reihenfolge so gewählt habe, dass der Fehler nicht kam.

Sollte aber eigentlich nicht passieren --> Bug Report!

**Comment by StephanSchaller** [comment]
(Uups, I was in German mode ...)

**Comment by PavelBal** [comment]
Same behavior in Matlab!

**Comment by Yuri05** [comment]
>Same behavior in Matlab!

Not reproducible in Matlab. E.g. initializing 2 simulations and running them as shown below works fine.

```
initSimulation(xmlFile, 'none')
initSimulation(xmlFile, 'none','addFile',true)
processSimulation(1)
processSimulation(2)
```

Please attach your Matlab code

**Comment by PavelBal** [comment]
> Not reproducible in Matlab. E.g. initializing 2 simulations and running them as shown below works fine.

Sorry, I was referrring to the scaling factors...

**Comment by Yuri05** [comment]
>Sorry, I was referrring to the scaling factors...

Regarding the scale factors: please attach your Matlab code.

Regarding simulation initialization: not sure, how it's implemented in R. 
In Matlab, if you need more than 1 active simulation, you must use the 'addFile' option, otherwise every call to initSimulation will destroy the previously created one.
In any case, it's another story, so please open a separate issue for this.

**Comment by StephanSchaller** [comment]
> In any case, it's another story, so please open a separate issue for this.

He did, yesterday (#59)

**Comment by PavelBal** [comment]
> Regarding the scale factors: please attach your Matlab code.

Also attached the test models.
[ScalingFactors.zip](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/1875243/ScalingFactors.zip)




```
%ScaleFactors_1 fails with AbsTol = 1e-10 and runs with AbsTol = 1e-15
%ScaleFactors_opt runs with AbsTol = 1e-10

%Initialize and run simulations as exported from MoBi
xmlSF_1 = './ScaleFactors_1.xml';
xmlSF_opt = './ScaleFactors_opt.xml';

simIdx_1 = 1;
simIdx_opt = 2;

%Init and run the first simulation
initSimulation(xmlSF_1, 'none', 'addFileAtIndex', simIdx_1);
processSimulation(simIdx_1);

%Init and run the second simulation
initSimulation(xmlSF_opt, 'none', 'addFileAtIndex', simIdx_opt);
processSimulation(simIdx_opt);

%Get simulation results
[xVals1, yVals1] = getSimulationResult('*|Organism|a', simIdx_1);
[xVals_opt, yVals_opt] = getSimulationResult('*|Organism|a', simIdx_opt);

%Plot results. Results are identical (as they should be)
hold all
plot(xVals1, yVals1, 'b');
plot(xVals_opt, yVals_opt, 'g*');

%Change scaling factors of ScaleFactors_opt (i.e., the second simulation) to 1
initStruct = [];
initStruct = initParameter(initStruct, 'AbsTol', 'always');
%Get a list of all initial values.
    [~,desc] = existsSpeciesInitialValue('*', simIdx_opt, 'parametertype', 'readonly');
    %Initialize all species start values that are not defined by a formula
    %ANOTHER PROBLEM - WE CAN NOT CHANGE SCALE FACTORS OF FORMULA-DEFINED
    %SPECIES WIHTOUT INITIALIZING THEM!!!
    for i = 2:size(desc,1)
        path = desc{i, 2};
        isFormula = desc{i, 6};
        if ~isFormula
            initStruct = initSpeciesInitialValue(initStruct, path, 'never');
        end
    end

    %Initilize the second simulation with spcies start values set to
    %variable
disp('init last sim');
initSimulation(xmlSF_opt, initStruct, 'addFileAtIndex', simIdx_opt);

%Set scaling factors to 1
    for i = 2:size(desc,1)
        path = desc{i, 2};
            setSpeciesInitialValue(1, path, simIdx_opt, 'property', 'ScaleFactor');
    end

%Change AbsTol to 1e-15
%DCI_Info_opt = setParameter(1e-15, path_id = "AbsTol", DCI_Info = DCI_Info_opt);

disp('Process simulation after changing scaling factors');
%Run the second simulation with changed scale factors
processSimulation(simIdx_opt);
[xVals_opt, yVals_opt] = getSimulationResult('*|Organism|a', simIdx_opt);

%Plot results - they should be identical, but are not.
plot(xVals_opt, yVals_opt, 'r:');

hold off
```

![image](https://user-images.githubusercontent.com/25903040/38301915-405ede32-3801-11e8-9f74-4c9ea099288f.png)

**Comment by Yuri05** [comment]
Closing in favor of the new R-Toolbox.
