### ISSUE TITLE
processSimulation(): include TryCatch error-handling

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/R-Toolbox#53]
In Matlab, return value of `processSimulation()` was boolean to  flag if simulation was successful, but it would always continue, no matter what.

Now in R, return value is taken up by `DCI_Info`, and failed simulations are handled with errors.
I am building my own `tryCatch()` routine around `processSimulation`, but maybe we should integrate sth. in `processSimulation ` (maybe optional so it can be set via the function inputs like `"stopOnErrors"` or `"continueWithWarning"`...) so it can  be used easily.

Thoughts?

**Comment by PavelBal** [comment]
How does the simulation continue in Matlab, if it is not successful? As far I can remember, the routine returned the results up to the time point where the error occured, but I am not sure.

**Comment by Yuri05** [comment]
`processSimulation` in Matlab always returns boolean `success`-value.
After that it's up to the caller how to handle it. 
[s. example call](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/blob/a58efef1cfcc9bc960d98bb07ee16b8df718999f/src/code/engine_library/generateSimResult.m#L106)

As `processSimulation` have `TryCatch ` error-handling inside, it doesn't throw exceptions in case of failure (at least in Matlab. Not sure if R implementation does).

**Comment by StephanSchaller** [comment]
No, R Implementation does not.
