### ISSUE TITLE
Submit R-Toolbox to CRAN

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#56]
I recently gave a workshop on the R-Toolbox and was asked why the toolbox is not released on CRAN. What do you think, would it be an option?

Having the package on CRAN could help to increase the acceptance of the toolbox. In theory, the users could exchange their models as XML and use them in R, without having the need to install the whole OSP suite.

**Comment by msevestre** [comment]
Do you know what needs to be done in order to release to CRAN?
The package is already available as a [zip file](https://github.com/Open-Systems-Pharmacology/R-Toolbox/releases/download/v7.2.0.5/MoBiToolboxForR_7.2.0.zip) so it is possible to use it without using the setup as far as I know

**Comment by StephanSchaller** [comment]
> The package is already available as a zip file so it is possible to use it without using the setup as far as I know

Yes, that 's correct. 
I don't know the process to release to CRAN. There might be sth. like a quality control process to be able to release to CRAN (as they sometimes remove packages from CRAN).

**Comment by PavelBal** [comment]
> Do you know what needs to be done in order to release to CRAN?

Nope. I could take a look how time-consuming it would be.
