### ISSUE TITLE
Error when two simulations are initilized consequentially without being run in between

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#59]
```
DCI1 <- initSimulation(xml1,initStruct)
DCI2 <- initSimulation(xml2,initStruct)
# run the original simulations
DCI1 <- processSimulation(DCI_Info = DCI1)
DCI2 <- processSimulation(DCI_Info = DCI2)
```

results in

```
 Error in updateSimulationInputs(DCI_Info) : 
  Component handle 258639328 is invalid! 
```

, while
```

DCI1 <- initSimulation(xml1,initStruct)
DCI1 <- processSimulation(DCI_Info = DCI1)

DCI2 <- initSimulation(xml2,initStruct)
DCI2 <- processSimulation(DCI_Info = DCI2)
```

works.

**Comment by StephanSchaller** [comment]
From #52 

> Regarding simulation initialization: not sure, how it's implemented in R.

In R, the DCI_INFO is a local variable, so you create a new one for each 'initSimulation'. Normally, working with different DCI_Infos should not be a problem, but apparently that's only the case if you have first initialized & simulated each xml sequentially.

**Comment by Yuri05** [comment]
Can you please down-track the problematic R-code (init;init;process;process) to the list of **_pure DCI calls_** and paste the code here?
