### ISSUE TITLE
runit.saveSimulationToXML fails

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#64]
test.CheckXMLAllVariables: FAILURE !! (check number 1) Error in checkEquals(dci_info[idx], savedDCI[idx]) : Component “InputTab”: Component “AllParameters”: Component “Value”: Mean absolute difference: Inf Component “InputTab”: Component “AllParameters”: Component “ParameterType”: 2629 string mismatches Component “InputTab”: Component “AllParameters”: Component “Formula”: 2629 string mismatches Component “InputTab”: Component “VariableParameters”: Component “Value”: Mean absolute difference: Inf Component “InputTab”: Component “VariableParameters”: Component “ParameterType”: 2629 string mismatches Component “InputTab”: Component “VariableParameters”: Component “Formula”: 2629 string mismatches Component “InputTab”: Component “AllSpecies”: Component “IsFormula”: Mean relative difference: 1 Component “InputTab”: Component “AllSpecies”: Component “Formula”: 205 string mismatches Component “InputTab”: Component “VariableSpecies”: Component “IsFormula”: Mean relative difference: 1 Component “InputTab”: Component “VariableSpecies”: Component “Formula”: 205 string mismatches Component “ReferenceTab”: Component “AllParameters”: Component “Value”: Mean absolute difference: Inf Component “ReferenceTab”: Component “AllParameters”: Component “ParameterType”: 2629 string mismatches Component “ReferenceTab”: Component “AllParameters”: Component “Formula”: 2629 string mismatches Component “ReferenceTab”: Component “VariableParameters”: Component “Value”: Mean absolute difference: Inf Component “ReferenceTab”: Component “VariableParameters”: Component “ParameterType”: 2629 string mismatches Component “ReferenceTab”: Component “VariableParameters”: Component “Formula”: 2629 string mismatches Component “ReferenceTab”: Component “AllSpecies”: Component “IsFormula”: Mean relative difference: 1 Component “ReferenceTab”: Component “AllSpecies”: Component “Formula”: 205 string mismatches Component “ReferenceTab”: Component “VariableSpecies”: Component “IsFormula”: Mean relative difference: 1 Component “ReferenceTab”: Component “VariableSpecies”: Component “Formula”: 205 string mismatches 

@PavelBal

**Comment by PavelBal** [comment]
@Yuri please clarify whether it is a bug or just wrong formulation of the test.

This is what the test does:

```
simModelXML <- "./tests/models/black american girl.xml"
  dci_info <- initSimulation(XML=simModelXML, whichInitParam="all")
  path <- file.path(getwd(), "TestSim.xml")
  
  savedFile <- saveSimulationToXML(XML=path, DCI_Info = dci_info)
  savedDCI <- initSimulation(XML=savedFile, whichInitParam="all")
  
  idx <- which(names(dci_info) != "Handle")
  checkEquals(dci_info[idx], savedDCI[idx])
```

1) Initialize simulation with `whichInitParam="all"` into DCI_info_1
2) Save the simulation as XML
3) Initialize the new saved XML into DCI_info_2
4) Compare DCI_info1 and DCI_info_2. According to the test, they should be identical.

They are not because all formulas in the new XML are set to constant values, while they are actually formulas in the original XML. To my understanding it matches the anticipated behavior - before writing into XML, the simulation is finalized in SimModel. During finalization, formulas of constant parameters are calculated and substituted by constant values. Thus, the new created XML differs from the original.

Now, one could argue whether it is a bug or a feature. Which one is it?`

Also @StephanSchaller and @msevestre can contribute with your thoughts.

**Comment by StephanSchaller** [comment]
if I understand correctly what you did, than this is "anticipated" behaviour. Initialized parameters are always handled as constants. BUT: AFAIK the DCI_Info is not properly updated following the initialization but only once it has been put through a DCI call... (i.e. at least I remember sth. like this from MATLAB)... @Yuri05 ?

Try putting the original DCI_Info through processSimulation and then compare again to savedDCI..?

**Comment by yuri** [comment]
@PavelBal I think you've got the wrong Yuri tagged. :)

**Comment by Yuri05** [comment]
>Try putting the original DCI_Info through processSimulation and then compare again to savedDCI..?

Exactly, call `ProcessSimulation `directly after `initSimulation `for both simulations and compare dci_infos after that.
