### ISSUE TITLE
Toolbox 7.2.0 does not work with R 3.5

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#71]
Something was changed in R 3.5, so the toolbox needs to be re-compiled with R 3.5 to run.

**Comment by msevestre** [comment]
How new is 3.5? Is anyone still using 3.4 out there aside from us?

**Comment by PavelBal** [comment]
3.5 has been released on 2018-04-23, so relatively new.

**Comment by msevestre** [comment]
@PavelBal ok cool.

**Comment by msevestre** [comment]
A few questions for you :
- [ ] would a version compile with 3.5 also works with 3.4?
- [ ] We are using some very old stuff to compile to toolbox I believe:

Check that out here
[R](https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/develop/appveyor.yml#L22)
[RTools](https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/develop/appveyor.yml#L27)

According to you, shouldn't we move to some newer version here?

**Comment by PavelBal** [comment]
Compiled with 3.4 -> runs only with 3.4 (or later i.e. <=3.4). Compiled with 3.5 -> runs only with >=3.5. So to make sure new releases will work with new R versions, we have to move to >= 3.5. Or, if we want to be real heroes, offert two versions - for >=3.5 and for <=3.4.

**Comment by msevestre** [comment]
>or, if we want to be real heroes, offert two versions - for >=3.5 and for <=3.4.

lol

**Comment by msevestre** [comment]
We won't be heroes here but will support R >3.5 from now on once  #96 is merged and tested
