### ISSUE TITLE
getParameter() returns a wrong value for "IsFormula

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#76]
Similar to #60 

```
dci_info <- initSimulation(XML=simModelXML, whichInitParam="none")
getParameter("black american girl|MoleculeProperties|CYP3A4|Permeability", DCI_Info = dci_info, options = list(Property = "IsFormula"))
$Value
[1] 0

$Index
[1] 4205
```

`black american girl|MoleculeProperties|CYP3A4|Permeability` is given by a formula:

`    <P id="9236" entityId="5uLKIdupTEufePpzFypVkA" name="Permeability" path="black american girl|MoleculeProperties|CYP3A4" unit="cm/min" persistable="0" formulaId="9239" />`

but the returned value for "isFormula" is 0!

**Comment by msevestre** [comment]
Is the formula 9239 a constant by any chance?

**Comment by PavelBal** [comment]
Hmm, yes, it is evaluated to a constant... Makes sense.

**Comment by PavelBal** [comment]
In Matlab, the returned value is "1". I would assume it should work identically in R.
