### ISSUE TITLE
Bug: Value "Inf" in xml files is read as "0"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#77]
Some parameters, e.g., "Enzyme|Permeability", have non-defined values (see screenshot)

![image](https://user-images.githubusercontent.com/25903040/40916549-6f286bfa-6800-11e8-8919-21ab8fdd3578.png)

In the toolbox, these values are evaluated to "Inf". If saving a simulation where such a parameter was initialized to xml, the formula gets a constant value "Inf" stored in the XML.

So far, it is the default behavior. When initializing such a simulation, the value becomes "0".

**Comment by PavelBal** [comment]
I think this is in SimModel, isn't it?

**Comment by PavelBal** [comment]
Please advise.

**Comment by Yuri05** [comment]
@PavelBal Do we have the same problem with NaN-values in xml?

**Comment by PavelBal** [comment]
Yes, both "Inf" and "NaN" are returned as 0 when initializing the xml.

**Comment by Yuri05** [comment]
Closing in favor of the new R-Toolbox.
