### ISSUE TITLE
getParameter/SpeciesInitialValue/Observer should stop when a parameter is not found

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#78]
At the moment, it just gives a warning.

This was changed in #41 #42, but for the consistency with the setter methods should be reverted.

The caller must first check with "existsParameter/.../..." before trying to access the parameter.

**Comment by msevestre** [comment]
Why the sudden change of mind? This was requested by you if I recall properly?

**Comment by PavelBal** [comment]
Got confused by the unit tests. Now I recall why the change from error to warning was necessary and pull this issue back. Sorry.
