### ISSUE TITLE
Feature request: Simulate to steady-state

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#81]
Especially for QSP models with endogenous production of compounds, it is often necessary to start the simulation with initial state other then 0 for the most molecules. To determine this initial state, the model can be simulated for a long time and the end state set to the initial state. A simplified workflow looks like this:

1) Simulate the model with default initial state for long time
2) Iterate through all outputs and the speciesInitialValues to the end value of the output
3) Optionally, save end result to an excel file to be able to load it in MoBi.

There are some questions:
1) MoBi-import requires the column "Neg. values allowed" for every entry. How do I get this information from within R?
2) Initial values given by an equation should not be overwritten. However, getSpeciesInitialValue() returns a wrong value for "IsFormula" (#60). How to overcome this limitation?
3) What are the special cases that should be ignored or treated in a different way?
3a) How to treat the EndogenousIgG compartment?
3b) How to treat saliva values?

Anything else?

**Comment by PavelBal** [comment]
I know @KatrinCoboeken was interested in such a feature for MoBi. Katrin, do you have any thoughts on this (perhaps hat it is done in Matlab?)

**Comment by PavelBal** [comment]
Other questions:
-can/should we introduce some cut-off value below which the results can be considered as "numerical noise"?

-should we calculate scale divisors in the same step and apply/write them into xls?

**Comment by Yuri05** [comment]
>can/should we introduce some cut-off value below which the results can be considered as "numerical noise"?

This information is available, however not forwarded to Matlab/R. Could be added e.g. as new column attribute for calculated variables and observers.

**Comment by PavelBal** [comment]
> This information is available, however not forwarded to Matlab/R. Could be added e.g. as new column attribute for calculated variables and observers.

Would be great.

**Comment by KatrinCoboeken** [comment]
Hi Pavel,
I have only a very limited matlab implementation without considering your special cases. I was used to calculate a multi application.

[example_setEndValuesToStartValues.txt](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/2083017/example_setEndValuesToStartValues.txt)

**Comment by Yuri05** [comment]
@PavelBal There are a lot of topics being discussed here: simulation with steady-state initial values, numeric noise level, non-negative values, scale divisors, ...
Would suggest that you create one issue per topic, otherwise the discussion will become nontransparent
