### ISSUE TITLE
getEndSimulationResults()

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#83]
Do we want to have a function getEndSimulationResults(), which behaves similarly to getSimulationResults() but only returns the last value of the simulation?

Pros:
-A convenient way to get steady-state results.

**Comment by StephanSchaller** [comment]
Sorry, I kind of read this but forgot I had this coded already (it's just a minor change from the original `getSimulationResults()` (the very last `for` loop):


[getEndSimulationResult.zip](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/2134880/getEndSimulationResult.zip)
