### ISSUE TITLE
"Negative Values Allowed" - information?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#93]
Is there a possibility to retrieve the value of the flag "Negative Values Allowed" for the species in the Toolbox? So, is it stored in the DCI or somewhere?

**Comment by Yuri05** [comment]
The value is stored in XML model files, but not propagated via DCI. Please make a feature request in SimModel

**Comment by Yuri05** [comment]
Closing in favor of https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/issues/55
