### ISSUE TITLE
MobiSettings should stop if the library path is not found

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#98]
Currently, it returns "itself" (the function) instead of a list "MobiSettings". It should just stop because the lib isnt there.

**Comment by msevestre** [comment]
should be done with https://github.com/Open-Systems-Pharmacology/R-Toolbox/commit/9bcb9e80bd55ecc67ed3bf420a84658ac2e0d6a8
